sudo: required
dist: trusty
language: python
cache: pip
deploy:
  provider: pypi
  user: struts2spring
  password: SomeDefaultText
  distributions: sdist bdist_wheel
python:
  - "3.6"

branches:
  only:
    - master

# command to install dependencies
addons:
  apt:
    packages:
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev

# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install libwebkitgtk-dev libjpeg-dev libtiff-dev libgtk2.0-dev libsdl1.2-dev freeglut3 freeglut3-dev libnotify-dev
  - echo "SIX_INSTALLATION"
  - travis_wait 60 sudo pip install -Uv six
  - echo "WXPYTHON_INSTALLATION"
  - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython
 #travis_wait 60 sudo pip install -Uv wxpython
  - echo "WXPYTHON_INSTALLATION_FINISHED"
  - "pip install requests coveralls nose-htmloutput nose coverage"
  - echo "INSTALLATION_FINISHED"
  - pip install -r requirements.txt
  - pip install -U pytest
  - python -V

# command to run tests
script:
  - pytest
after_success:
- coveralls
notifications:
  email:
    recipients:
      - certifyexam0@gmail.com
    on_success: always # default: change
    on_failure: always # default: always